import {HeroUIProvider} from "@heroui/react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <HeroUIProvider>
          {children}
      </HeroUIProvider>
      </body>
      </html>
  )
}
